const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('#loader')?.classList.add('hide'),600));
const nav=$('.nav-wrap'), progress=$('#progress');
window.addEventListener('scroll',()=>{const y=scrollY; nav.classList.toggle('scrolled',y>30); const h=document.documentElement.scrollHeight-innerHeight; progress.style.width=(h?y/h*100:0)+'%'; updateActiveNav();});
function updateActiveNav(){const sections=$$('main section[id]');let current='home';for(const s of sections){if(scrollY>=s.offsetTop-160) current=s.id} $$('.nav-link').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${current}`));}
const observer=new IntersectionObserver((entries)=>entries.forEach((e)=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12}); $$('.reveal').forEach(el=>observer.observe(el));
const countObserver=new IntersectionObserver((entries)=>entries.forEach((e)=>{if(!e.isIntersecting)return; const el=e.target; const target=+el.dataset.count; let start=0; const step=Math.max(1,Math.ceil(target/25)); const timer=setInterval(()=>{start+=step;if(start>=target){start=target;clearInterval(timer)}el.textContent=start},36);countObserver.unobserve(el)}),{threshold:.7}); $$('[data-count]').forEach(x=>countObserver.observe(x));
$$('.skill-tab').forEach(btn=>btn.addEventListener('click',()=>{ $$('.skill-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active'); const cat=btn.dataset.tab; $$('.skill-card').forEach(card=>{card.style.display=cat==='all'||card.dataset.cat===cat?'':'none'}) }));
const menuBtn=$('#menuBtn'), navLinks=$('#navLinks');menuBtn?.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});$$('.nav-link').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
const dot=$('#cursorDot'), ring=$('#cursorRing');window.addEventListener('mousemove',(e)=>{if(!dot||!ring)return;dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px';ring.animate({left:`${e.clientX}px`,top:`${e.clientY}px`},{duration:180,fill:'forwards'})});
$$('.tilt').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*7}deg) rotateX(${y*-6}deg)`});card.addEventListener('mouseleave',()=>card.style.transform='')});
$$('.magnetic').forEach(btn=>btn.addEventListener('mousemove',e=>{const r=btn.getBoundingClientRect();const x=e.clientX-r.left-r.width/2;const y=e.clientY-r.top-r.height/2;btn.style.transform=`translate(${x*.06}px,${y*.06}px)`}),false);$$('.magnetic').forEach(btn=>btn.addEventListener('mouseleave',()=>btn.style.transform=''));
const canvas=$('#particles'),ctx=canvas.getContext('2d');let pts=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;pts=Array.from({length:Math.min(70,Math.floor(innerWidth/16))},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.5+.3}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);for(const p of pts){p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba(100,180,255,.5)';ctx.fill();}requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize);
$('#contactForm').addEventListener('submit',(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const to='zadew.contact@gmail.com';const subject=encodeURIComponent(f.get('subject'));const body=encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\n\n${f.get('message')}`);window.location.href=`mailto:${to}?subject=${subject}&body=${body}`;$('#formStatus').textContent='Opening your email app…';});
$('#year').textContent=new Date().getFullYear();
